# Generated by Django 4.0.4 on 2022-06-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
