# Generated by Django 4.0.4 on 2022-06-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0003_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
